# Generated by Django 6.0.5 on 2026-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=100)),
                ('min_attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('min_participation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(max_length=20)),
            ],
        ),
    ]
