# Generated by Django 6.0.5 on 2026-05-20 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_university_user_university'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('faculty', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('emotional_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
