# Generated by Django 6.0.5 on 2026-05-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_student'),
        ('appointments', '0003_alter_appointment_student'),
        ('reports', '0002_alter_report_student'),
        ('students', '0002_remove_student_user_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
