# Generated by Django 6.0.5 on 2026-05-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('VERY_GOOD', 'Muy bien'), ('GOOD', 'Bien'), ('NEUTRAL', 'Regular'), ('BAD', 'Mal'), ('VERY_BAD', 'Muy mal')], max_length=20)),
                ('stress_level', models.IntegerField()),
                ('sleep_hours', models.IntegerField()),
                ('motivation_level', models.IntegerField()),
                ('feels_supported', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='students.studentprofile')),
            ],
        ),
    ]
