# Generated by Django 6.0.5 on 2026-05-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('students', '0002_remove_student_user_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.studentprofile'),
        ),
    ]
