# Generated by Django 6.0.5 on 2026-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], max_length=20),
        ),
    ]
