# Generated by Django 6.0.5 on 2026-05-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_psychologist_and_more'),
        ('students', '0002_remove_student_user_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='students.studentprofile'),
        ),
    ]
